// lib/modality.ts — interim: the ground-truth modality per protocol, read from the benchmark's
// groundtruth_library_generation_workflow.json files (final_outputs[].modality, enum order:
// gene expression, genomic DNA, feature barcode, sgRNA, chromatin accessibility; joined with " + ").
// Used only when /protocols does not send `modality` yet; the backend rename replaces this table.
// Generated 2026-09-29 from libstruct-bench/runs (73 protocols).

export const GT_MODALITY: Record<string, string> = {
  "10x_chromium_3_feature_barcoding": "gene expression + feature barcode",
  "10x_chromium_3_gene_expression_v1": "gene expression",
  "10x_chromium_3_gene_expression_v2": "gene expression",
  "10x_chromium_3_gene_expression_v3": "gene expression",
  "10x_chromium_3_gene_expression_v3_1": "gene expression",
  "10x_chromium_3_gene_expression_v4": "gene expression",
  "10x_chromium_5_gene_expression_v1_1": "gene expression",
  "10x_chromium_5_gene_expression_v2": "gene expression",
  "10x_chromium_5_gene_expression_v3": "gene expression",
  "10x_chromium_5_immune_profiling_feature_barcoding_v1_1": "gene expression + feature barcode",
  "10x_chromium_5_immune_profiling_feature_barcoding_v2": "gene expression + feature barcode",
  "10x_chromium_5_immune_profiling_feature_barcoding_v3": "gene expression + feature barcode",
  "10x_chromium_single_cell_atac_v2": "chromatin accessibility",
  "10x_chromium_single_cell_multiome_atac_plus_gene_expression": "gene expression + chromatin accessibility",
  "bd_rhapsody_wta": "gene expression",
  "cel_seq": "gene expression",
  "cel_seq2": "gene expression",
  "ch_atac_seq": "chromatin accessibility",
  "crispr_sciatac": "sgRNA + chromatin accessibility",
  "ddseq_scatac_seq": "chromatin accessibility",
  "ddseq_single_cell_3_rna_seq_kit": "gene expression",
  "dr_seq": "gene expression + genomic DNA",
  "drop_seq": "gene expression",
  "fipresci": "gene expression",
  "flash_seq": "gene expression",
  "hydrop_atac": "chromatin accessibility",
  "hydrop_rna": "gene expression",
  "indrop_v1": "gene expression",
  "indrop_v2": "gene expression",
  "issaac_seq_droplet": "gene expression + chromatin accessibility",
  "issaac_seq_facs": "gene expression + chromatin accessibility",
  "itchip_seq": "genomic DNA",
  "lianti": "genomic DNA",
  "malbac": "genomic DNA",
  "mars_seq_v2": "gene expression",
  "microsplit": "gene expression",
  "microwell_seq": "gene expression",
  "paired_seq": "gene expression + chromatin accessibility",
  "petri_seq": "gene expression",
  "pi_atac_seq": "chromatin accessibility",
  "pip_seq_v4": "gene expression",
  "plate_scatac_seq": "chromatin accessibility",
  "quartz_seq": "gene expression",
  "s3_atac": "chromatin accessibility",
  "scbs_seq": "genomic DNA",
  "scdam_and_t_seq": "gene expression + genomic DNA",
  "scdamid": "genomic DNA",
  "scdnase_seq": "chromatin accessibility",
  "sci_atac_seq": "chromatin accessibility",
  "sci_atac_seq3": "chromatin accessibility",
  "sci_rna_seq": "gene expression",
  "sci_rna_seq3": "gene expression",
  "scifi_atac_seq": "chromatin accessibility",
  "scifi_rna_seq": "gene expression",
  "scrb_seq": "gene expression",
  "scrrbs": "genomic DNA",
  "scths_seq": "chromatin accessibility",
  "seq_well_s3": "gene expression",
  "share_seq": "gene expression + chromatin accessibility",
  "smart_seq": "gene expression",
  "smart_seq2": "gene expression",
  "smart_seq3": "gene expression",
  "smart_seq3xpress": "gene expression",
  "snare_seq": "gene expression + chromatin accessibility",
  "spear_atac": "sgRNA + chromatin accessibility",
  "split_seq": "gene expression",
  "strt_seq": "gene expression",
  "strt_seq_2i": "gene expression",
  "strt_seq_c1": "gene expression",
  "tang_2009": "gene expression",
  "txci_atac_seq": "chromatin accessibility",
  "vasa_drop": "gene expression",
  "vasa_plate": "gene expression",
};

/** What to show in the modality column: the backend's value, else the ground-truth table, else the legacy family. */
export const modalityOf = (p: { id: string; modality?: string; family?: string }): string =>
  p.modality ?? GT_MODALITY[p.id] ?? p.family ?? "unclassified";
